apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart-page-rs
  namespace: srishti-ns
spec:   
  replicas: 3
  selector:
    matchLabels:
      web: cart
  template: #defines which application we deploy [pod defintion]
    metadata:
      labels:
        web: cart
    spec: #defines behavior of the pod and its container
      containers:
      - name: cart-container
        image: muralisocial123/cart-page-test:1.0
        # resources:
        #   limits:
        #     memory: "100Mi"
        #     cpu: "100m"
        ports:
          - containerPort: 3000
